#!/system/bin/sh

echo enter a number

read a

echo enter a number

read b

i=1

while [ i -le 10 ]

do

k=`ls`

echo hello

    echo `expr $a + $b `

    if [ $i -eq 5 ]

    then

break #continue exit

fi

i=`expr $i+1`

    done

if [ -b readme.txt ]

then

echo yes

fi

case $a in

1) echo "a is one"

;;

2) echo "a is two"

;;

*) echo "there is no match"

esac 
for data in {1..10.1}# 1 is miss step
do 
echo $data #o/p=1.....10
done 
for k in 1 2 3 4 5
do 
echo $k
done
for ((a=1;a<10;a++))
do

do

echo $a
done

done

for h in ls pwd mkdir 
do

do

echo $h
done

